const contains = (a, b) => a.toLowerCase().indexOf(b.toLowerCase()) !== -1

export const getImage = (name = '') => {
  if (contains(name, 'Telev')) return 'tv.jpg'
  if (contains(name, 'Audifonos Alambricos')) return 'headphones.jpg'
  if (contains(name, 'Audifonos Bluetooth')) return 'bluethoot-headphones.jpg'
  if (contains(name, 'Barra de sonido')) return 'soundbar.jpg'
  if (contains(name, 'Bocina Bluetooth')) return 'bluethoot-speaker.jpg'
  if (contains(name, 'Bocina exterior')) return 'exterior-speaker.png'
  if (contains(name, 'Camara inalambrica para interior')) return 'wireless-camera.jpg'
  if (contains(name, 'Camara para exterior')) return 'outdoor-camera.jpg'
  if (contains(name, 'Camara para Interior')) return 'indoor-camera.jpg'
  if (contains(name, 'Disco Duro')) return 'hard-drive.jpg'
  if (contains(name, 'DVR')) return 'dvr.jpg'
  if (contains(name, 'Karaoke')) return 'karaoke.jpg'
  if (contains(name, 'Lamparas automáticas')) return 'automatic-lamp.jpg'
  if (contains(name, 'Minicomponente')) return 'minicomponent.jpg'
  if (contains(name, 'RAM')) return 'ram.jpg'
  if (contains(name, 'BluRay')) return 'bluray.jpg'
  if (contains(name, 'DVD')) return 'dvd.jpg'
  if (contains(name, 'Sensores de movimiento')) return 'movement-sensor.jpg'
  if (contains(name, 'Sensores de puerta')) return 'door-sensor.jpg'
  if (contains(name, 'SSD')) return 'ssd.jpg'
  if (contains(name, 'Teatro en casa')) return 'home-theatre.jpg'
  if (contains(name, 'Tornamesa')) return 'tornamesa.jpg'
  if (contains(name, 'Reflectores')) return 'reflector.jpg'
}
