use online_donations;
insert into country (name ) values ('Saudi Arabia');
insert into country (name ) values ('Russia');
insert into country (name ) values ('Sweden');
insert into country (name ) values ('Japan');
insert into country (name ) values ('Brazil');
insert into country (name ) values ('Armenia');
insert into country (name ) values ('Afghanistan');
insert into country (name ) values ('United Kingdom');
insert into country (name ) values ('Philippines');
insert into country (name ) values ('China');
insert into country (name ) values ('Somalia');
insert into country (name ) values ('United States');
insert into country (name ) values ('Sierra Leone');
insert into country (name ) values ('Argentina');
insert into country (name ) values ('Cuba');
insert into country (name ) values ('Indonesia');
insert into country (name ) values ('Slovenia');
insert into country (name ) values ('Andorra');
insert into country (name ) values ('Croatia');
insert into country (name ) values ('Czech Republic');
insert into country (name ) values ('Lesotho');
insert into country (name ) values ('Ukraine');
insert into country (name ) values ('Poland');
insert into country (name ) values ('Dominican Republic');
insert into country (name ) values ('Denmark');
insert into country (name ) values ('Bolivia');
insert into country (name ) values ('Gambia');
insert into country (name ) values ('Bulgaria');
insert into country (name ) values ('Canada');
insert into country (name ) values ('Palestinian Territory');
insert into country (name ) values ('Guatemala');
insert into country (name ) values ('France');
insert into country (name ) values ('Portugal');
insert into country (name ) values ('New Caledonia');
insert into country (name ) values ('Tanzania');
insert into country (name ) values ('Thailand');
insert into country (name ) values ('Kazakhstan');
insert into country (name ) values ('Luxembourg');
insert into country (name ) values ('Nigeria');
insert into country (name ) values ('Peru');


