use online_donations;
insert into institution (name, description, id_country) values ('Subin', 'volutpat quam pede lobortis ligula sit amet eleifend pede libero', 19);
insert into institution (name, description, id_country) values ('Holdlamis', 'faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor', 25);
insert into institution (name, description, id_country) values ('Stronghold', 'aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer', 16);
insert into institution (name, description, id_country) values ('Greenlam', 'ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin', 26);
insert into institution (name, description, id_country) values ('Overhold', 'sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec', 26);
insert into institution (name, description, id_country) values ('Lotlux', 'vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio', 17);
insert into institution (name, description, id_country) values ('Subin', 'platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis', 5);
insert into institution (name, description, id_country) values ('Cookley', 'magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce', 3);
insert into institution (name, description, id_country) values ('Domainer', 'id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui', 9);
insert into institution (name, description, id_country) values ('Aerified', 'aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus', 21);
insert into institution (name, description, id_country) values ('Viva', 'augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo', 29);
insert into institution (name, description, id_country) values ('Cardify', 'donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in', 14);
insert into institution (name, description, id_country) values ('Lotstring', 'massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh', 6);
insert into institution (name, description, id_country) values ('Biodex', 'tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus', 20);
insert into institution (name, description, id_country) values ('Vagram', 'non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros', 38);
insert into institution (name, description, id_country) values ('Keylex', 'proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut', 16);
insert into institution (name, description, id_country) values ('Tampflex', 'id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia', 21);
insert into institution (name, description, id_country) values ('Wrapsafe', 'enim sit amet nunc viverra dapibus nulla suscipit ligula in', 4);
insert into institution (name, description, id_country) values ('Greenlam', 'tortor id nulla ultrices aliquet maecenas leo odio condimentum id', 31);
insert into institution (name, description, id_country) values ('Voyatouch', 'elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel', 8);
insert into institution (name, description, id_country) values ('Namfix', 'enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus', 4);
insert into institution (name, description, id_country) values ('Otcom', 'auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio', 12);
insert into institution (name, description, id_country) values ('Subin', 'metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci', 18);
insert into institution (name, description, id_country) values ('It', 'sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in', 25);
insert into institution (name, description, id_country) values ('Trippledex', 'in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec', 40);
insert into institution (name, description, id_country) values ('Hatity', 'morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra', 22);
insert into institution (name, description, id_country) values ('Cookley', 'magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere', 31);
insert into institution (name, description, id_country) values ('Sub-Ex', 'non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing', 12);
insert into institution (name, description, id_country) values ('Bytecard', 'quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices', 12);
insert into institution (name, description, id_country) values ('Voyatouch', 'risus praesent lectus vestibulum quam sapien varius ut blandit non interdum', 19);
insert into institution (name, description, id_country) values ('Fintone', 'nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse', 39);
insert into institution (name, description, id_country) values ('Tresom', 'erat curabitur gravida nisi at nibh in hac habitasse platea dictumst', 21);
insert into institution (name, description, id_country) values ('Wrapsafe', 'sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus', 33);
insert into institution (name, description, id_country) values ('Tres-Zap', 'ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris', 29);
insert into institution (name, description, id_country) values ('Stim', 'fusce congue diam id ornare imperdiet sapien urna pretium nisl', 24);
insert into institution (name, description, id_country) values ('Solarbreeze', 'quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum', 26);
insert into institution (name, description, id_country) values ('Aerified', 'integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla', 23);
insert into institution (name, description, id_country) values ('Tempsoft', 'ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero', 18);
insert into institution (name, description, id_country) values ('Mat Lam Tam', 'interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum', 39);
insert into institution (name, description, id_country) values ('Viva', 'ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis', 6);
insert into institution (name, description, id_country) values ('Tresom', 'id pretium iaculis diam erat fermentum justo nec condimentum neque', 28);
insert into institution (name, description, id_country) values ('Sub-Ex', 'porta volutpat quam pede lobortis ligula sit amet eleifend pede libero', 24);
insert into institution (name, description, id_country) values ('Lotlux', 'proin risus praesent lectus vestibulum quam sapien varius ut blandit non interdum in ante vestibulum ante ipsum', 8);
insert into institution (name, description, id_country) values ('Andalax', 'viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non', 33);
insert into institution (name, description, id_country) values ('Kanlam', 'tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus', 6);
insert into institution (name, description, id_country) values ('Temp', 'maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat', 8);
insert into institution (name, description, id_country) values ('Flexidy', 'sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea', 16);
insert into institution (name, description, id_country) values ('Biodex', 'mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus', 15);
insert into institution (name, description, id_country) values ('Tin', 'in sagittis dui vel nisl duis ac nibh fusce lacus', 16);
insert into institution (name, description, id_country) values ('Bamity', 'mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit', 38);
insert into institution (name, description, id_country) values ('Bitchip', 'tellus semper interdum mauris ullamcorper purus sit amet nulla quisque', 15);
insert into institution (name, description, id_country) values ('Sub-Ex', 'fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit', 9);
insert into institution (name, description, id_country) values ('Stim', 'mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus', 25);
insert into institution (name, description, id_country) values ('Alphazap', 'non interdum in ante vestibulum ante ipsum primis in faucibus orci luctus', 3);
insert into institution (name, description, id_country) values ('Sonair', 'diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris', 4);
insert into institution (name, description, id_country) values ('Quo Lux', 'a libero nam dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan', 26);
insert into institution (name, description, id_country) values ('Cardify', 'in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec', 15);
insert into institution (name, description, id_country) values ('Zontrax', 'magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum', 9);
insert into institution (name, description, id_country) values ('Namfix', 'integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede', 12);
insert into institution (name, description, id_country) values ('Asoka', 'id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed', 23);
insert into institution (name, description, id_country) values ('Alphazap', 'mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec', 8);
insert into institution (name, description, id_country) values ('Stringtough', 'eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum', 4);
insert into institution (name, description, id_country) values ('Mat Lam Tam', 'at turpis a pede posuere nonummy integer non velit donec diam neque', 20);
insert into institution (name, description, id_country) values ('Tempsoft', 'fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in', 31);
insert into institution (name, description, id_country) values ('Job', 'eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis', 29);
insert into institution (name, description, id_country) values ('Redhold', 'semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis vel dapibus at', 6);
insert into institution (name, description, id_country) values ('Konklux', 'ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit', 40);
insert into institution (name, description, id_country) values ('Bigtax', 'justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie', 31);
insert into institution (name, description, id_country) values ('Voltsillam', 'venenatis tristique fusce congue diam id ornare imperdiet sapien urna', 39);
insert into institution (name, description, id_country) values ('Wrapsafe', 'ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin', 5);
insert into institution (name, description, id_country) values ('Andalax', 'at velit vivamus vel nulla eget eros elementum pellentesque quisque', 14);
insert into institution (name, description, id_country) values ('Viva', 'ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis', 6);
insert into institution (name, description, id_country) values ('Viva', 'convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante', 12);
insert into institution (name, description, id_country) values ('Keylex', 'est risus auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum', 16);
insert into institution (name, description, id_country) values ('Overhold', 'proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in', 21);
insert into institution (name, description, id_country) values ('Stronghold', 'orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel', 2);
insert into institution (name, description, id_country) values ('Y-find', 'lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in', 34);
insert into institution (name, description, id_country) values ('Namfix', 'commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt', 26);
insert into institution (name, description, id_country) values ('Voyatouch', 'imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris', 28);
insert into institution (name, description, id_country) values ('Zathin', 'nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum', 19);
insert into institution (name, description, id_country) values ('Fix San', 'nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin', 22);
insert into institution (name, description, id_country) values ('Biodex', 'eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in', 4);
insert into institution (name, description, id_country) values ('Tempsoft', 'turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc', 25);
insert into institution (name, description, id_country) values ('Namfix', 'lectus vestibulum quam sapien varius ut blandit non interdum in ante vestibulum ante ipsum', 20);
insert into institution (name, description, id_country) values ('Asoka', 'primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus', 28);
insert into institution (name, description, id_country) values ('Ventosanzap', 'rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis', 38);
insert into institution (name, description, id_country) values ('Matsoft', 'lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna', 38);
insert into institution (name, description, id_country) values ('Asoka', 'morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus', 18);
insert into institution (name, description, id_country) values ('Veribet', 'lobortis ligula sit amet eleifend pede libero quis orci nullam', 23);
insert into institution (name, description, id_country) values ('Prodder', 'ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit', 31);
insert into institution (name, description, id_country) values ('Y-Solowarm', 'erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea', 1);
insert into institution (name, description, id_country) values ('Redhold', 'parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id', 34);
insert into institution (name, description, id_country) values ('Sonair', 'cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien', 12);
insert into institution (name, description, id_country) values ('Konklab', 'nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet', 5);
insert into institution (name, description, id_country) values ('Bigtax', 'curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu', 38);
insert into institution (name, description, id_country) values ('Sonair', 'ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet', 30);
insert into institution (name, description, id_country) values ('Zathin', 'libero ut massa volutpat convallis morbi odio odio elementum eu interdum', 28);
insert into institution (name, description, id_country) values ('Alpha', 'lorem id ligula suspendisse ornare consequat lectus in est risus auctor', 5);
insert into institution (name, description, id_country) values ('Gembucket', 'augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet', 23);
insert into institution (name, description, id_country) values ('Latlux', 'curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non', 40);
insert into institution (name, description, id_country) values ('Sonsing', 'sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in', 3);
insert into institution (name, description, id_country) values ('Redhold', 'eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat', 4);
insert into institution (name, description, id_country) values ('Tres-Zap', 'a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum', 12);
insert into institution (name, description, id_country) values ('Zathin', 'porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in', 15);
insert into institution (name, description, id_country) values ('Keylex', 'dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut', 16);
insert into institution (name, description, id_country) values ('Bitchip', 'magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi', 17);
insert into institution (name, description, id_country) values ('Fintone', 'aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis', 22);
insert into institution (name, description, id_country) values ('Fixflex', 'eleifend quam a odio in hac habitasse platea dictumst maecenas ut', 20);
insert into institution (name, description, id_country) values ('Alphazap', 'lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id', 26);
insert into institution (name, description, id_country) values ('Fintone', 'ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi', 3);
insert into institution (name, description, id_country) values ('Lotstring', 'vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci', 6);
insert into institution (name, description, id_country) values ('Andalax', 'ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec', 39);
insert into institution (name, description, id_country) values ('Solarbreeze', 'luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est', 14);
insert into institution (name, description, id_country) values ('Fixflex', 'nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula', 4);
insert into institution (name, description, id_country) values ('Alpha', 'sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis', 21);
insert into institution (name, description, id_country) values ('Hatity', 'faucibus accumsan odio curabitur convallis duis consequat dui nec nisi', 24);
insert into institution (name, description, id_country) values ('Opela', 'sapien varius ut blandit non interdum in ante vestibulum ante ipsum', 34);
insert into institution (name, description, id_country) values ('Zamit', 'tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in', 25);
insert into institution (name, description, id_country) values ('Biodex', 'volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo', 18);
insert into institution (name, description, id_country) values ('Stringtough', 'nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget', 8);
insert into institution (name, description, id_country) values ('Hatity', 'justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec', 24);
